
name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.6
      - 
        name: Install dependencies
        run: |
          go version
          go get .
      -
        name: Run build
        run: go build .
      -
        name: Run testing
        run: go test -v
        
  deployment:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: vigilantebagel777/go-produce
        tag_with_ref: true
