# This is a basic workflow to help you get started with Actions

name: deploy

on:
  deployment:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.ref == ‘refs/heads/main’ && github.event_name == ‘push’ }}

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Docker registry
      uses: docker/build-push-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: vigilantebagel777/go-produce
        tag_with_ref: true
